# Generated by Django 4.2.25 on 2025-10-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_document_folder_delete_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='share_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
