# Generated by Django 4.2.25 on 2025-10-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rule_type', models.CharField(choices=[('preset', 'Preset'), ('custom', 'Custom'), ('ai', 'AI-Assisted')], max_length=20)),
                ('pattern', models.TextField(blank=True, help_text='For custom rules: regex pattern or word/phrase to flag')),
                ('is_active', models.BooleanField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
